[build-system]
requires = ["setuptools==75.3.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gamesup-recommendation-api"
version = "0.1.0"
description = "API de recommandation GamesUP"
readme = "readme.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "fastapi==0.115.0",
    "uvicorn[standard]==0.31.0",
    "pydantic==2.9.2",
    "pydantic-settings==2.5.2",
    "pandas==2.2.3",
    "scikit-learn==1.5.2",
    "scipy==1.14.1",
    "joblib==1.4.2",
]

[tool.setuptools.packages.find]
include = ["gamesup_api*"]
